In [218]:
import numpy as np


In [219]:
np.__version__

'2.0.1'

In [220]:
arr = np.array([25,10,20,30,40,50,60])
arr

array([25, 10, 20, 30, 40, 50, 60])

In [221]:
ls = [25,10,20,30,40,50,60]
arr = np.array(ls)
arr

array([25, 10, 20, 30, 40, 50, 60])

In [222]:
type(arr)

numpy.ndarray

In [223]:
arr.ndim

1

In [224]:
arr.size

7

In [225]:
arr.dtype

dtype('int64')

In [226]:
arr = np.array([25,10,20,30,40,50,60,25.2])
arr

array([25. , 10. , 20. , 30. , 40. , 50. , 60. , 25.2])

In [227]:
arr.dtype

dtype('float64')

In [228]:
arr = np.array([25,10,20,30,40,50,60])
arr

array([25, 10, 20, 30, 40, 50, 60])

In [229]:
arr[4]

np.int64(40)

In [230]:
np.mean(arr)

np.float64(33.57142857142857)

In [231]:
np.median

<function median at 0x00000274D1705D30>

In [232]:
np.random.randint()

TypeError: randint() takes at least 1 positional argument (0 given)

In [68]:
import random

In [20]:
random.randint(1,9)

7

In [69]:
arr = np.random.randint(1,450,500)
arr

array([129, 251, 282, 213, 314, 209, 141, 410, 174, 208, 263, 296,  35,
        46, 255, 136, 291, 154, 176,  17, 165, 444, 418, 398, 295, 206,
       354, 407, 218, 426, 404, 446, 248,  83,  34,  18, 169, 127,  65,
       449, 438, 295, 248, 162,  20, 130, 132, 157, 401,  61, 300, 136,
       368,  70,  28, 342, 161, 216, 442, 446, 225, 116, 275, 365, 395,
       447, 353, 415, 135, 266, 434, 429, 444,  74,  14, 226,  83, 370,
       401,  96, 448, 304, 245, 250,  50, 180, 408, 306, 370, 333, 362,
        52, 111, 389, 218,  64, 428, 158, 142, 367,  33, 222, 161, 400,
       235, 404,  65, 124, 252, 264,  10, 340,  68, 426, 223, 226, 141,
       161,  67, 367, 340, 288, 115, 271,  41, 114, 219, 189, 245,  62,
       364, 224, 104, 289, 292,  46, 411,  54, 135, 332, 169, 249, 121,
       189, 232, 165, 118,  37, 378, 250, 126, 356, 399, 379, 270, 236,
       441,   3, 418, 249, 219, 405, 139, 392,  52, 321,  31,  60, 442,
       141, 146,  16,   7, 230,  47,  17, 396, 430,   1, 272, 27

In [70]:
arr < 100

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False,  True, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True, False,  True, False, False,  True, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False, False,  True, False,
       False, False,  True, False,  True, False, False, False, False,
       False,  True, False, False, False, False, False,  True, False,
       False, False,

In [71]:
arr[arr < 100]

array([35, 46, 17, 83, 34, 18, 65, 20, 61, 70, 28, 74, 14, 83, 96, 50, 52,
       64, 33, 65, 10, 68, 67, 41, 62, 46, 54, 37,  3, 52, 31, 60, 16,  7,
       47, 17,  1, 78, 41, 84, 44, 77, 96, 17, 26, 99, 83, 42, 65, 90, 63,
       60, 94, 99, 70, 64, 88,  2, 98, 56, 62,  8, 76, 25, 53, 15,  4, 69,
       47, 42, 23,  6, 73, 34, 20, 43,  9, 36, 26, 26, 40, 11, 18,  4, 49,
       59, 48, 95, 29, 62, 64, 96, 52,  1, 22, 18, 30, 96, 78, 71, 16, 75,
       85, 12, 85, 26, 52, 73,  1, 48], dtype=int32)

In [72]:
len(arr[arr < 100])

110

2D array

In [73]:
ls = [[1,2,3],
      [4,5,6],
      [7,8,9]]
ls

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [74]:
type(ls)

list

In [75]:
arr2 = np.array(ls)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
arr2.ndim

2

In [77]:
arr2[0]

array([1, 2, 3])

In [78]:
arr2[2]

array([7, 8, 9])

In [79]:
arr2[0:1]

array([[1, 2, 3]])

In [140]:
arr2[-1]

array([7, 8, 9])

In [141]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [142]:
arr2[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [143]:
arr2[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [147]:
arr2[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [146]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [148]:
arr2[-2:,-3:]

array([[4, 5, 6],
       [7, 8, 9]])

In [181]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [182]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [186]:
np.linspace(1,50,10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

3D array

In [234]:
ls = [[[1, 2, 3], [4, 5, 6],
       [7, 8, 9]],[[1, 2, 3],
      [4, 5, 6], [7, 8, 9]],
       [[1, 2, 3], [4, 5, 6],
        [7, 8, 9]],[[1, 2, 3],
         [4, 5, 6], [7, 8, 9]]]
ls

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [239]:
arr3 = np.array(ls)

In [240]:
arr3.ndim

3

In [241]:
arr3.shape

(4, 3, 3)

In [242]:
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [243]:
arr3[0:4,0,:]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [244]:
arr3[ :,1:3,1:3 ]

array([[[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]]])

In [245]:
arr3.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [246]:
arr3.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [247]:
arr3.reshape(36,)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])